"""main

Revision ID: 60ac9d724475
Revises: 
Create Date: 2025-09-28 09:46:20.286579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60ac9d724475'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_status'), ['status'], unique=False)

    op.create_table('client_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('billing_email', sa.String(length=255), nullable=True),
    sa.Column('default_currency', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_profile_user_id'), ['user_id'], unique=True)

    op.create_table('freelancer_education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('school', sa.String(length=160), nullable=True),
    sa.Column('degree', sa.String(length=160), nullable=True),
    sa.Column('field', sa.String(length=160), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('freelancer_education', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_freelancer_education_user_id'), ['user_id'], unique=False)

    op.create_table('freelancer_experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('company', sa.String(length=160), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('skills', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('freelancer_experience', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_freelancer_experience_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_freelancer_experience_user_id'), ['user_id'], unique=False)

    op.create_table('freelancer_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('headline', sa.String(length=160), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('portfolio_url', sa.String(length=255), nullable=True),
    sa.Column('payout_email', sa.String(length=255), nullable=True),
    sa.Column('nda_signed_at', sa.DateTime(), nullable=True),
    sa.Column('approval_status', sa.String(length=20), nullable=True),
    sa.Column('kyc_status', sa.String(length=20), nullable=True),
    sa.Column('kyc_checked_at', sa.DateTime(), nullable=True),
    sa.Column('rating_avg', sa.Float(), nullable=True),
    sa.Column('completed_tasks', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('freelancer_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_freelancer_profile_approval_status'), ['approval_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_freelancer_profile_kyc_status'), ['kyc_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_freelancer_profile_user_id'), ['user_id'], unique=True)

    op.create_table('support_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_ticket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_ticket_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_ticket_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_ticket_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_ticket_ticket_id'), ['ticket_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_support_ticket_user_id'), ['user_id'], unique=False)

    op.create_table('task_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('deadline_at', sa.DateTime(), nullable=True),
    sa.Column('client_budget', sa.Float(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_request_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_request_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_request_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_request_deadline_at'), ['deadline_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_request_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_request_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_request_title'), ['title'], unique=False)

    op.create_table('assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('accept_expires_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('declined_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['assignee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignment_assigned_by'), ['assigned_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_assignee_id'), ['assignee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_task_id'), ['task_id'], unique=False)

    op.create_table('file_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=50), nullable=True),
    sa.Column('path', sa.String(length=512), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('mime', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file_asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_asset_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_asset_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_asset_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_asset_uploaded_at'), ['uploaded_at'], unique=False)

    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('gateway_ref', sa.String(length=120), nullable=True),
    sa.Column('pesapal_tracking_id', sa.String(length=64), nullable=True),
    sa.Column('pesapal_merchant_ref', sa.String(length=64), nullable=True),
    sa.Column('gateway', sa.String(length=32), nullable=True),
    sa.Column('gateway_status', sa.String(length=32), nullable=True),
    sa.Column('gateway_meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('join_url', sa.String(length=512), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('invite_uid', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task_request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_invite_uid'), ['invite_uid'], unique=True)
        batch_op.create_index(batch_op.f('ix_meeting_scheduled_for'), ['scheduled_for'], unique=False)
        batch_op.create_index(batch_op.f('ix_meeting_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_meeting_task_id'), ['task_id'], unique=False)

    op.create_table('payout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('freelancer_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['freelancer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('proposed_price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('pay_option', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('client_counter_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('client_counter_currency', sa.String(length=10), nullable=True),
    sa.Column('client_counter_reason', sa.Text(), nullable=True),
    sa.Column('client_counter_status', sa.String(length=20), nullable=True),
    sa.Column('client_counter_at', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quote_client_counter_status'), ['client_counter_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_quote_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_quote_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_quote_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quote_valid_until'), ['valid_until'], unique=False)

    op.create_table('support_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=True),
    sa.Column('author_role', sa.String(length=10), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_ticket.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_message_ticket_id'), ['ticket_id'], unique=False)

    op.create_table('work_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('by_user_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('files_json', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kyc_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('doc_type', sa.String(length=50), nullable=True),
    sa.Column('id_number', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('file_id_front', sa.Integer(), nullable=True),
    sa.Column('file_id_back', sa.Integer(), nullable=True),
    sa.Column('file_id_selfie', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_id_back'], ['file_asset.id'], ),
    sa.ForeignKeyConstraint(['file_id_front'], ['file_asset.id'], ),
    sa.ForeignKeyConstraint(['file_id_selfie'], ['file_asset.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('support_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['support_message.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_ticket.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_attachment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_attachment_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_attachment_ticket_id'), ['ticket_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_attachment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_attachment_ticket_id'))
        batch_op.drop_index(batch_op.f('ix_support_attachment_message_id'))

    op.drop_table('support_attachment')
    op.drop_table('kyc_submission')
    op.drop_table('work_submission')
    with op.batch_alter_table('support_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_message_ticket_id'))

    op.drop_table('support_message')
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quote_valid_until'))
        batch_op.drop_index(batch_op.f('ix_quote_task_id'))
        batch_op.drop_index(batch_op.f('ix_quote_status'))
        batch_op.drop_index(batch_op.f('ix_quote_created_at'))
        batch_op.drop_index(batch_op.f('ix_quote_client_counter_status'))

    op.drop_table('quote')
    op.drop_table('payout')
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meeting_task_id'))
        batch_op.drop_index(batch_op.f('ix_meeting_status'))
        batch_op.drop_index(batch_op.f('ix_meeting_scheduled_for'))
        batch_op.drop_index(batch_op.f('ix_meeting_invite_uid'))

    op.drop_table('meeting')
    op.drop_table('invoice')
    with op.batch_alter_table('file_asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_asset_uploaded_at'))
        batch_op.drop_index(batch_op.f('ix_file_asset_task_id'))
        batch_op.drop_index(batch_op.f('ix_file_asset_owner_id'))
        batch_op.drop_index(batch_op.f('ix_file_asset_kind'))

    op.drop_table('file_asset')
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignment_task_id'))
        batch_op.drop_index(batch_op.f('ix_assignment_status'))
        batch_op.drop_index(batch_op.f('ix_assignment_created_at'))
        batch_op.drop_index(batch_op.f('ix_assignment_assignee_id'))
        batch_op.drop_index(batch_op.f('ix_assignment_assigned_by'))

    op.drop_table('assignment')
    with op.batch_alter_table('task_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_request_title'))
        batch_op.drop_index(batch_op.f('ix_task_request_status'))
        batch_op.drop_index(batch_op.f('ix_task_request_priority'))
        batch_op.drop_index(batch_op.f('ix_task_request_deadline_at'))
        batch_op.drop_index(batch_op.f('ix_task_request_created_at'))
        batch_op.drop_index(batch_op.f('ix_task_request_client_id'))
        batch_op.drop_index(batch_op.f('ix_task_request_category'))

    op.drop_table('task_request')
    with op.batch_alter_table('support_ticket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_ticket_user_id'))
        batch_op.drop_index(batch_op.f('ix_support_ticket_ticket_id'))
        batch_op.drop_index(batch_op.f('ix_support_ticket_status'))
        batch_op.drop_index(batch_op.f('ix_support_ticket_ip_address'))
        batch_op.drop_index(batch_op.f('ix_support_ticket_email'))

    op.drop_table('support_ticket')
    with op.batch_alter_table('freelancer_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_freelancer_profile_user_id'))
        batch_op.drop_index(batch_op.f('ix_freelancer_profile_kyc_status'))
        batch_op.drop_index(batch_op.f('ix_freelancer_profile_approval_status'))

    op.drop_table('freelancer_profile')
    with op.batch_alter_table('freelancer_experience', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_freelancer_experience_user_id'))
        batch_op.drop_index(batch_op.f('ix_freelancer_experience_created_at'))

    op.drop_table('freelancer_experience')
    with op.batch_alter_table('freelancer_education', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_freelancer_education_user_id'))

    op.drop_table('freelancer_education')
    with op.batch_alter_table('client_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_profile_user_id'))

    op.drop_table('client_profile')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_status'))
        batch_op.drop_index(batch_op.f('ix_user_role'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_created_at'))

    op.drop_table('user')
    # ### end Alembic commands ###
